grails/todo/grails-app/domain/es/ua/expertojava/todo/Category.groovy
package es.ua.expertojava.todo

import es.ua.expertojava.todo.Todo

class Category {

    String name
    String description

    static hasMany = [todos:Todo]

    static constraints = {
        name(blank:false)
        description(blank:true, nullable:true, maxSize:1000)
    }

    public Category(String nameCategory) {
        this.name = nameCategory;
    }

    String toString(){
        name
    }
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/Tag.groovy
package es.ua.expertojava.todo

class Tag {

    String name
    String color

    static hasMany = [todos:Todo]

    static constraints = {
        name(blank:false, nullable:false, unique:true)
        color shared: "rgbColor"


    }

    String toString(){
        name
    }
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/Todo.groovy
package es.ua.expertojava.todo

class Todo {
    String title
    String description
    Date date
    Date reminderDate
    String url
    Category category
    Boolean done
    Date dateCreated
    Date lastUpdated
    Date dateDone


    static hasMany = [tags:Tag]
    static belongsTo = [Tag]  //se encarga de los borrados en cascada

    static constraints = {
        title(blank:false)
        description(blank:true, nullable:true, maxSize:1000)
        date(nullable:false)
        reminderDate(nullable:true,
                validator: { val, obj ->
                    if (val && obj.date) {
                        return val.before(obj?.date)
                    }
                    return true
                }
        )
        url(nullable:true, url:true)
        category(nullable:true)
        done(blank:false, done:false)
        dateDone(nullable:true)
    }
    public Todo(String name, Date date) {
        this.title = name
        this.date = date
    }

    public Todo(String name, Date date, boolean done) {
        this.title = name
        this.date = date
        this.done = done
    }

    String toString(){
        title
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/CategoryController.groovy
package es.ua.expertojava.todo



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class CategoryController {

    CategoryService categoryService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Category.list(params), model:[categoryInstanceCount: Category.count()]
    }

    def show(Category categoryInstance) {
        respond categoryInstance
    }

    def create() {
        respond new Category(params)
    }

    @Transactional
    def save(Category categoryInstance) {
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'create'
            return
        }

        categoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'category.label', default: 'Category'), categoryInstance.name])
                redirect categoryInstance
            }
            '*' { respond categoryInstance, [status: CREATED] }
        }
    }

    def edit(Category categoryInstance) {
        respond categoryInstance
    }

    @Transactional
    def update(Category categoryInstance) {
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'edit'
            return
        }

        categoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Category.label', default: 'Category'), categoryInstance.id])
                redirect categoryInstance
            }
            '*'{ respond categoryInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Category categoryInstance) {

        if (categoryInstance == null) {
            notFound()
            return
        }

        categoryService.delete(categoryInstance)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Category.label', default: 'Category'), categoryInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'category.label', default: 'Category'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/TagController.groovy
package es.ua.expertojava.todo



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TagController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Tag.list(params), model:[tagInstanceCount: Tag.count()]
    }

    def show(Tag tagInstance) {
        respond tagInstance
    }

    def create() {
        respond new Tag(params)
    }

    @Transactional
    def save(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'create'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tag.label', default: 'Tag'), tagInstance.id])
                redirect tagInstance
            }
            '*' { respond tagInstance, [status: CREATED] }
        }
    }

    def edit(Tag tagInstance) {
        respond tagInstance
    }

    @Transactional
    def update(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'edit'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Tag.label', default: 'Tag'), tagInstance.id])
                redirect tagInstance
            }
            '*'{ respond tagInstance, [status: OK] }
        }
    }

    def redireccionDelete(Tag tagInstance) {
        respond tagInstance
    }

    @Transactional
    def delete(Tag tagInstance) {

        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'delete'
            return
        }

        tagInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Tag.label', default: 'Tag'), tagInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }



    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tag.label', default: 'Tag'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/TodoController.groovy
package es.ua.expertojava.todo



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TodoController {

    CategoryService categoryService
    TodoService todoService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Todo.list(params), model:[todoInstanceCount: Todo.count()]
    }

    def show(Todo todoInstance) {
        respond todoInstance
    }

    def create() {
        respond new Todo(params)
    }

    @Transactional
    def save(Todo todoInstance) {
        if (todoInstance == null) {
            notFound()
            return
        }

        if (todoInstance.hasErrors()) {
            respond todoInstance.errors, view:'create'
            return
        }

        todoService.saveTodo(todoInstance)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'todo.label', default: 'Todo'), todoInstance.id])
                redirect todoInstance
            }
            '*' { respond todoInstance, [status: CREATED] }
        }
    }

    def edit(Todo todoInstance) {
        respond todoInstance
    }

    @Transactional
    def update(Todo todoInstance) {
        if (todoInstance == null) {
            notFound()
            return
        }

        if (todoInstance.hasErrors()) {
            respond todoInstance.errors, view:'edit'
            return
        }

        todoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Todo.label', default: 'Todo'), todoInstance.id])
                redirect todoInstance
            }
            '*'{ respond todoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Todo todoInstance) {

        if (todoInstance == null) {
            notFound()
            return
        }

        todoService.delete(todoInstance)


        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Todo.label', default: 'Todo'), todoInstance.title])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'todo.label', default: 'Todo'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def listNextTodos(Integer days) {
        respond todoService.getNextTodos(days, params),
                model:[todoInstanceCount: todoService.countNextTodos(days)],
                view:"index"
    }

    def listByCategory() {
        respond Todo.list(params), model:[categoryInstanceList: categoryService.listCategories()]
    }

    def listTodoByCategory(){
        List<String> listaCategorias = new ArrayList<>();
        params.get("categoria").each { idCategoria ->
            listaCategorias.add(Long.valueOf(idCategoria));
        }
        respond Todo.list(params), model:[listTodosByCategorySelected: todoService.listTodosByCategory(listaCategorias)]
    }

    def listLastTodosDone(){
        respond Todo.list(params), model:[listaTodos: todoService.lastTodosDone(23) ], view:'listTodoByCategory'

    }

}

grails/todo/grails-app/views/todo/_form.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>



<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'title', 'error')} required">
	<label for="title">
		<g:message code="todo.title.label" default="Title" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="title" required="" value="${todoInstance?.title}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="todo.description.label" default="Description" />
		
	</label>
	<g:textArea name="description" cols="40" rows="5" maxlength="1000" value="${todoInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'date', 'error')} required">
	<label for="date">
		<g:message code="todo.date.label" default="Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="date" precision="day"  value="${todoInstance?.date}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'reminderDate', 'error')} ">
	<label for="reminderDate">
		<g:message code="todo.reminderDate.label" default="Reminder Date" />
		
	</label>
	<g:datePicker name="reminderDate" precision="day"  value="${todoInstance?.reminderDate}" default="none" noSelection="['': '']" />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'url', 'error')} ">
	<label for="url">
		<g:message code="todo.url.label" default="Url" />
		
	</label>
	<g:field type="url" name="url" value="${todoInstance?.url}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'category', 'error')} ">
	<label for="category">
		<g:message code="todo.category.label" default="Category" />
		
	</label>
	<g:select id="category" name="category.id" from="${es.ua.expertojava.todo.Category.list()}" optionKey="id" value="${todoInstance?.category?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'done', 'error')} ">
	<label for="done">
		<g:message code="todo.done.label" default="Done" />
		
	</label>
	<g:checkBox name="done" value="${todoInstance?.done}" />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'dateDone', 'error')} required">
	<label for="dateDone">
		<g:message code="todo.dateDone.label" default="Date Done" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="dateDone" precision="day"  value="${todoInstance?.dateDone}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'tags', 'error')} ">
	<label for="tags">
		<g:message code="todo.tags.label" default="Tags" />
		
	</label>
	

</div>

grails/todo/grails-app/views/todo/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-todo" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${todoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${todoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:todoInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails/todo/grails-app/views/todo/edit.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-todo" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${todoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${todoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:todoInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${todoInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails/todo/grails-app/views/todo/index.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li><g:link class="home" controller="todo" action="listByCategory"><g:message code="default.list.label" args="[entityName]" /></g:link></li>

			</ul>
		</div>
		<div id="list-todo" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<g:sortableColumn property="edit" title="${message(code: 'todo.edit.label', default: 'Modify')}" />

						<g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'Title')}" />
					
						%{--<g:sortableColumn property="description" title="${message(code: 'todo.description.label', default: 'Description')}" />--}%
					
						<g:sortableColumn property="date" title="${message(code: 'todo.date.label', default: 'Date')}" />
					
						%{--<g:sortableColumn property="reminderDate" title="${message(code: 'todo.reminderDate.label', default: 'Reminder Date')}" />--}%
					
						<g:sortableColumn property="url" title="${message(code: 'todo.url.label', default: 'Url')}" />


						<th><g:message code="todo.category.label" default="Category" /></th>

						<g:sortableColumn property="done" title="${message(code: 'todo.done.label', default: 'Done')}" />


					</tr>
				</thead>
				<tbody>
				<g:each in="${todoInstanceList}" status="i" var="todoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td>
						<g:form url="[resource:todoInstance, action:'delete']" method="DELETE">
							<fieldset class="buttons">
								<g:link class="edit" action="edit" resource="${todoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
								<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
							</fieldset>
						</g:form>
						</td>
					
						<td><g:link action="show" id="${todoInstance.id}">${fieldValue(bean: todoInstance, field: "title")}</g:link></td>
					
						%{--<td>${fieldValue(bean: todoInstance, field: "description")}</td>--}%
					
						<td><g:formatDate date="${todoInstance.date}" /></td>
					
						%{--<td><g:formatDate date="${todoInstance.reminderDate}" /></td>--}%
					
						<td>${fieldValue(bean: todoInstance, field: "url")}</td>
					
						<td>${fieldValue(bean: todoInstance, field: "category")}</td>

						<td><todo:printIconFromBoolean value="${todoInstance.done}"/></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${todoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails/todo/grails-app/views/todo/listByCategory.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
        <li><g:link class="listByCategory" action="listByCategory"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
    </ul>
</div>
<div id="list-todo" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${todoInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${todoInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
<g:form url="[resource:todoInstance, action:'listTodoByCategory']">

    <table>
        <thead>
        <tr>
            <g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'Title')}" />
        </tr>
        </thead>
        <tbody>
        <g:each in="${categoryInstanceList}" status="i" var="categoryInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:checkBox name="categoria" id="${fieldValue(bean: categoryInstance, field: "id")}" value="${fieldValue(bean: categoryInstance, field: "id")}"/>${fieldValue(bean: categoryInstance, field: "name")}</td>
            </tr>
        </g:each>

        </tbody>
    </table>
    <fieldset class="buttons">
        <g:link class="edit" action="listTodoByCategory" resource="${todoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
        <g:actionSubmit class="list" action="listTodoByCategory" value="${message(code: 'default.button.list.label', default: 'ListByCategory')}" />
        <g:actionSubmit class="update" action="listLastTodosDone" value="Ultimas tareas terminadas en las ultimas 4 horas" />
    </fieldset>
</g:form>
</div>
</body>
</html>

grails/todo/grails-app/views/todo/listTodoByCategory.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
    <title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
<div id="edit-todo" class="content scaffold-edit" role="main">
    <h1>Seleccionar categorias</h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${todoInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${todoInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource:todoInstance, action:'listTodoByCategory']">
        <table>
            <thead>
            <tr>
                <g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'nombre')}" />
            </tr>
            </thead>
            <tbody>
            <g:each in="${listTodosByCategorySelected}" status="i" var="todoInstance">
                <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                    <td>${fieldValue(bean: todoInstance, field: "title")}</td>

                </tr>
            </g:each>

            </tbody>
        </table>
        <fieldset class="buttons">
            <g:link class="edit" action="listTodoByCategory" resource="${todoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
            <g:actionSubmit class="delete" action="listTodoByCategory" value="${message(code: 'default.button.delete.label', default: 'Delete')}" />
        </fieldset>
    </g:form>
</div>
<a href="#edit-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
        <li><g:link class="listByCategory" action="listByCategory">Mostrar tareas seleccionadas</g:link></li>
    </ul>
</div>
</body>
</html>